version: '1'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80"
    links:
      - php-fpm
    volumes:
      - ./:/app
      - ./.docker/nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/nginx/var/log/nginx:/var/log/nginx

  php-fpm:
    image: hiqdev/php:7.3-fpm
    links:
      - pgsql
    volumes:
      - ./:/app
      - ./.docker/php/var/log/php:/var/log/php
  pgsql:
    image: postgres:11.0
