CREATE DATABASE `camagru`;

CREATE TABLE `camagru`.`users` (
  ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(16) NOT NULL,
  PASSWD VARCHAR(25) NOT NULL,
  EMAIL VARCHAR(25) NOT NULL,
  LOG_STAT INT DEFAULT 0,
  CMT VARCHAR(256)
);

CREATE TABLE `camagru`.`posts` (
  ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  USER VARCHAR(16) NOT NULL,
  PICT VARCHAR(100) NOT NULL,
  CMT varchar(256)
);