BEGIN TRANSACTION;


-- Insert into kek (a) values (124);

-- CREATE DATABASE `camagru`;

-- CREATE TABLE lololol (
--     a int
-- );

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  ID SERIAL PRIMARY KEY NOT NULL,
  NAME VARCHAR(16) NOT NULL,
  PASSWD VARCHAR(25) NOT NULL,
  EMAIL VARCHAR(25) NOT NULL,
  LOG_STAT INT DEFAULT 0,
  CMT VARCHAR(256)
);

DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
  ID SERIAL PRIMARY KEY NOT NULL,
  "USER" VARCHAR(16) NOT NULL,
  PICT VARCHAR(100) NOT NULL,
  CMT varchar(256)
);

COMMIT;